from __future__ import annotations

"""
Canonical commercial metadata for Teknovashop products.

This file is the single backend source of truth for presentation/release state.
Geometry lives in model_contracts.py and builders; the frontend consumes this
metadata from /catalog/products instead of maintaining an independent V2 list.
"""

PRODUCT_METADATA = {
    "vesa-adapter": {
        "name": "Adaptador VESA (2 patrones)",
        "family": "Montaje",
        "description": "Placa adaptadora configurable entre dos patrones VESA.",
        "tips": ["Confirma ambos patrones antes de imprimir","Aumenta perímetros si la carga lo requiere"],
        "marketing_image": "/images/products/professional/vesa-adapter.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "cable-tray": {
        "name": "Bandeja de Cables",
        "family": "Cableado",
        "description": "Organizador bajo mesa modular para alimentación, hubs y cableado.",
        "tips": ["Ancla cada 20-30 cm","Aumenta infill si cargas peso"],
        "marketing_image": "/images/products/professional/cable-tray.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "vesa-shelf": {
        "name": "Bandeja VESA",
        "family": "Montaje",
        "description": "Bandeja técnica con montaje VESA y geometría configurable.",
        "tips": ["Comprueba el patrón VESA","Valida el despeje detrás del monitor"],
        "marketing_image": "/images/products/professional/vesa-shelf.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "ssd-holder": {
        "name": "Caddy SSD 2.5 a 3.5",
        "family": "Electrónica",
        "description": "Adaptador paramétrico para montar un SSD de 2.5 pulgadas en bahía de 3.5.",
        "tips": ["Tornillos M3x6","PETG si hay temperatura elevada"],
        "marketing_image": "/images/products/professional/ssd-holder.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "enclosure-ip65": {
        "name": "Caja técnica con tapa",
        "family": "Electrónica",
        "description": "Caja configurable con tapa para electrónica y pequeños proyectos.",
        "tips": ["Respeta el espesor mínimo","Comprueba el ajuste de la tapa"],
        "marketing_image": "/images/products/professional/enclosure-ip65.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "raspi-case": {
        "name": "Caja Raspberry Pi",
        "family": "Electrónica",
        "description": "Caja ventilada configurable para Raspberry Pi.",
        "tips": ["Revisa los puertos de tu modelo","Añade ventilación si hay carga térmica"],
        "marketing_image": "/images/products/professional/raspi-case.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "mic-arm-clip": {
        "name": "Clip Brazo Mic",
        "family": "Cableado",
        "description": "Clip paramétrico para ordenar o fijar el brazo de micrófono.",
        "tips": ["Comprueba el diámetro","PLA o PETG según flexión"],
        "marketing_image": "/images/products/professional/mic-arm-clip.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "cable-clip": {
        "name": "Clip de Cable",
        "family": "Cableado",
        "description": "Clip configurable para ordenar cables de distinto diámetro.",
        "tips": ["Deja holgura suficiente","Imprime varios por trabajo"],
        "marketing_image": "/images/products/professional/cable-clip.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "wall-hook": {
        "name": "Colgador de Pared",
        "family": "Pared",
        "description": "Colgador paramétrico con placa de montaje y gancho reforzado.",
        "tips": ["Usa fijación adecuada","No excedas la carga prevista"],
        "marketing_image": "/images/products/professional/wall-hook.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "wall-bracket": {
        "name": "Escuadra de Pared",
        "family": "Pared",
        "description": "Escuadra estructural configurable para soporte mural.",
        "tips": ["Dimensiona según la carga","Aumenta perímetros si es estructural"],
        "marketing_image": "/images/products/professional/wall-bracket.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "qr-plate": {
        "name": "Placa de identificación / Texto",
        "family": "Maker",
        "description": "Placa personalizable con texto y perforaciones opcionales.",
        "tips": ["Valida profundidad de grabado","Comprueba la legibilidad del texto"],
        "marketing_image": "/images/products/professional/qr-plate.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "camera-plate": {
        "name": "Placa para Cámara",
        "family": "Foto y vídeo",
        "description": "Placa configurable con tornillo 1/4 y ranura de ajuste.",
        "tips": ["Comprueba la holgura","Valida la posición del tornillo"],
        "marketing_image": "/images/products/professional/camera-plate.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "phone-stand": {
        "name": "Soporte / Dock Móvil (USB-C)",
        "family": "Escritorio",
        "description": "Soporte inclinado configurable para móvil con gestión USB-C.",
        "tips": ["Ten en cuenta la funda","Valida el paso del cable"],
        "marketing_image": "/images/products/professional/phone-stand.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "headset-stand": {
        "name": "Soporte Auriculares",
        "family": "Escritorio",
        "description": "Soporte estable y configurable para auriculares.",
        "tips": ["Protege la zona de apoyo","Comprueba la altura útil"],
        "marketing_image": "/images/products/professional/headset-stand.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "router-mount": {
        "name": "Soporte de Router",
        "family": "Electrónica",
        "description": "Soporte paramétrico para router con base y respaldo.",
        "tips": ["Deja ventilación","Comprueba la holgura lateral"],
        "marketing_image": "/images/products/professional/router-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "go-pro-mount": {
        "name": "Soporte GoPro",
        "family": "Foto y vídeo",
        "description": "Montura compacta configurable compatible con geometría tipo GoPro.",
        "tips": ["Usa tornillería adecuada","Refuerza el área de la horquilla"],
        "marketing_image": "/images/products/professional/go-pro-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "hub-holder": {
        "name": "Soporte Hub USB",
        "family": "Electrónica",
        "description": "Alojamiento abierto configurable para hubs USB.",
        "tips": ["Mide el hub real","Añade holgura si usas adhesivo"],
        "marketing_image": "/images/products/professional/hub-holder.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "laptop-stand": {
        "name": "Soporte Laptop / Tablet",
        "family": "Escritorio",
        "description": "Soporte inclinado configurable para portátil o tablet.",
        "tips": ["No tapes la ventilación","Comprueba el grosor del equipo"],
        "marketing_image": "/images/products/professional/laptop-stand.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "vertical-laptop-dock": {
        "name": "Dock vertical para portátil",
        "family": "Escritorio",
        "description": "Dock paramétrico vertical para guardar el portátil ocupando el mínimo espacio.",
        "tips": ["Mide el grosor real con funda","Deja holgura suficiente para no marcar el equipo"],
        "marketing_image": "/images/products/premium-v1/vertical-laptop-dock.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "universal-mount-plate": {
        "name": "Placa universal de montaje",
        "family": "Montaje",
        "description": "Base multipropósito para crear montajes, transiciones y fijaciones técnicas.",
        "tips": ["Ajusta el espesor a la carga","Añade perforaciones desde Forge V2 cuando proceda"],
        "marketing_image": "/images/products/premium-v1/universal-mount-plate.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "mini-pc-mount": {
        "name": "Soporte mini-PC / NUC",
        "family": "Electrónica",
        "description": "Soporte abierto configurable para mini-PC, NUC y equipos compactos.",
        "tips": ["Reserva ventilación lateral","Mide conectores y salidas antes de imprimir"],
        "marketing_image": "/images/products/premium-v1/mini-pc-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "desk-grommet": {
        "name": "Pasacables de mesa",
        "family": "Cableado",
        "description": "Pasacables circular con diámetro interior y pestaña configurables.",
        "tips": ["Comprueba el diámetro del orificio de la mesa","Deja margen para conectores grandes"],
        "marketing_image": "/images/products/premium-v1/desk-grommet.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "under-desk-channel": {
        "name": "Canal bajo mesa",
        "family": "Cableado",
        "description": "Canal técnico para guiar mazos de cables y alimentación bajo escritorio.",
        "tips": ["Dimensiona el ancho según el mazo","Usa varios tramos para instalaciones largas"],
        "marketing_image": "/images/products/premium-v1/under-desk-channel.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "multi-device-dock": {
        "name": "Peana multi-dispositivo",
        "family": "Escritorio",
        "description": "Organizador configurable para varios móviles, tablets o dispositivos.",
        "tips": ["Ajusta el número de huecos","Mide el dispositivo más grueso antes de fabricar"],
        "marketing_image": "/images/products/premium-v1/multi-device-dock.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "webcam-monitor-mount": {
        "name": "Soporte webcam de monitor",
        "family": "Foto y vídeo",
        "description": "Montura compacta configurable para apoyar webcam o sensor sobre monitor.",
        "tips": ["Valida el grosor del monitor","Ajusta el ángulo antes de imprimir"],
        "marketing_image": "/images/products/premium-v1/webcam-monitor-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "network-switch-mount": {
        "name": "Soporte switch de red",
        "family": "Electrónica",
        "description": "Bandeja abierta para switches compactos con laterales y retención frontal.",
        "tips": ["No tapes ventilación ni puertos","Comprueba la profundidad con los cables conectados"],
        "marketing_image": "/images/products/premium-v1/network-switch-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "electronics-box": {
        "name": "Caja electrónica universal",
        "family": "Electrónica",
        "description": "Caja paramétrica universal con tapa separada para proyectos electrónicos.",
        "tips": ["Reserva espacio para conectores","Añade ventilación V2 según la carga térmica"],
        "marketing_image": "/images/products/premium-v1/electronics-box.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "controller-stand": {
        "name": "Soporte de mando",
        "family": "Escritorio",
        "description": "Peana configurable para mandos y dispositivos de mano.",
        "tips": ["Comprueba el ancho del mando","Ajusta el ángulo para un apoyo estable"],
        "marketing_image": "/images/products/premium-v1/controller-stand.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "drill-template": {
        "name": "Plantilla de perforación",
        "family": "Maker",
        "description": "Plantilla paramétrica para repetir perforaciones con paso y diámetro controlados.",
        "tips": ["Comprueba el paso antes de usarla","No la uses como guía estructural sin validar material"],
        "marketing_image": "/images/products/premium-v1/drill-template.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "drawer-divider": {
        "name": "Divisor de cajón",
        "family": "Organización",
        "description": "Separador paramétrico de cajón con pie de apoyo y altura configurables.",
        "tips": ["Mide el interior real del cajón","Divide piezas largas en módulos si tu cama es pequeña"],
        "marketing_image": "/images/products/premium-v1/drawer-divider.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "vesa-offset-adapter": {
        "name": "Adaptador VESA offset",
        "family": "Montaje",
        "description": "Placa paramétrica para desplazar un patrón de montaje manteniendo una base rígida.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": None,
        "stage": "engineering",
        "visual_source": "generated_preview",
    },
    "under-desk-mount": {
        "name": "Montura bajo mesa universal",
        "family": "Montaje",
        "description": "Soporte abierto configurable para fijar equipos y accesorios bajo escritorio.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/under-desk-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "perforated-mount-plate": {
        "name": "Placa técnica configurable",
        "family": "Montaje",
        "description": "Placa base reforzada para montajes técnicos y futuras operaciones V2.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": None,
        "stage": "engineering",
        "visual_source": "generated_preview",
    },
    "circular-pattern-adapter": {
        "name": "Adaptador de patrón circular",
        "family": "Montaje",
        "description": "Adaptador paramétrico para transiciones entre geometrías circulares y hubs.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": None,
        "stage": "engineering",
        "visual_source": "generated_preview",
    },
    "phone-landscape-stand": {
        "name": "Soporte móvil horizontal / vertical",
        "family": "Escritorio",
        "description": "Soporte estable configurable para móvil en orientación horizontal o vertical.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/phone-landscape-stand.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "smartwatch-stand": {
        "name": "Base para reloj inteligente",
        "family": "Escritorio",
        "description": "Peana paramétrica para reloj inteligente con base, mástil y apoyo superior.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/smartwatch-stand.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "cable-comb": {
        "name": "Peine de cables",
        "family": "Cableado",
        "description": "Organizador paramétrico para separar y alinear varios cables en paralelo.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/cable-comb.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "charger-retainer": {
        "name": "Retenedor de cargador",
        "family": "Cableado",
        "description": "Alojamiento abierto para inmovilizar cargadores y fuentes compactas.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/charger-retainer.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "zip-tie-anchor": {
        "name": "Anclaje para brida reutilizable",
        "family": "Cableado",
        "description": "Punto de fijación compacto para ordenar mazos con bridas reutilizables.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/zip-tie-anchor.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "nvme-caddy": {
        "name": "Caddy SSD / NVMe externo",
        "family": "Electrónica",
        "description": "Caddy paramétrico para cajas SSD/NVMe externas y pequeños dispositivos.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/nvme-caddy.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "power-supply-mount": {
        "name": "Soporte fuente de alimentación",
        "family": "Electrónica",
        "description": "Soporte configurable para fuentes y adaptadores de corriente compactos.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/power-supply-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "cold-shoe-adapter": {
        "name": "Adaptador cold-shoe",
        "family": "Foto y vídeo",
        "description": "Adaptador paramétrico para accesorios ligeros de cámara y montaje cold-shoe.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/cold-shoe-adapter.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "led-light-mount": {
        "name": "Soporte de luz LED",
        "family": "Foto y vídeo",
        "description": "Montura configurable con inclinación para pequeñas luces y paneles LED.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/led-light-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "audio-interface-mount": {
        "name": "Montura para interfaz de audio",
        "family": "Audio",
        "description": "Soporte abierto paramétrico para interfaces de audio de escritorio.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/audio-interface-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "battery-card-holder": {
        "name": "Organizador de baterías y tarjetas",
        "family": "Foto y vídeo",
        "description": "Organizador modular para baterías, tarjetas y accesorios pequeños.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/battery-card-holder.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "double-wall-hook": {
        "name": "Gancho doble de pared",
        "family": "Pared",
        "description": "Gancho mural doble configurable para colgar accesorios y objetos ligeros.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/double-wall-hook.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "compact-wall-shelf": {
        "name": "Estante mural compacto",
        "family": "Pared",
        "description": "Estante técnico pequeño con respaldo y refuerzos laterales.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/compact-wall-shelf.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "tool-holder": {
        "name": "Soporte modular de herramienta",
        "family": "Maker",
        "description": "Soporte paramétrico para organizar herramientas de uso frecuente.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/tool-holder.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "vesa-shelf-adapter": {
        "name": "Adaptador VESA a bandeja",
        "family": "Montaje",
        "description": "Adaptador híbrido para convertir una placa VESA en soporte de bandeja.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": None,
        "stage": "engineering",
        "visual_source": "generated_preview",
    },
    "universal-wall-mount": {
        "name": "Montura mural universal",
        "family": "Pared",
        "description": "Base mural configurable para equipos y accesorios de distintos tamaños.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/universal-wall-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "multipattern-transition-plate": {
        "name": "Placa de transición multipatrón",
        "family": "Montaje",
        "description": "Placa robusta para unir patrones de fijación distintos en una sola pieza.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": None,
        "stage": "engineering",
        "visual_source": "generated_preview",
    },
    "monitor-riser": {
        "name": "Elevador de monitor compacto",
        "family": "Escritorio",
        "description": "Elevador paramétrico de monitor con patas laterales y refuerzo posterior.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/monitor-riser.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "tablet-angle-stand": {
        "name": "Soporte tablet de ángulo configurable",
        "family": "Escritorio",
        "description": "Soporte paramétrico para tablet con ángulo, respaldo y apoyo frontal ajustables.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/tablet-angle-stand.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "microphone-desk-adapter": {
        "name": "Adaptador de micrófono a escritorio",
        "family": "Audio",
        "description": "Base paramétrica para adaptar accesorios de micrófono a una superficie de trabajo.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/microphone-desk-adapter.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "broom-tool-holder": {
        "name": "Soporte de escoba / herramienta",
        "family": "Pared",
        "description": "Soporte mural multiagarre para herramientas cilíndricas y útiles domésticos.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/broom-tool-holder.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "controller-wall-mount": {
        "name": "Soporte de mando mural",
        "family": "Pared",
        "description": "Montura mural compacta para mando con dos brazos de apoyo.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/controller-wall-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "speaker-wall-mount": {
        "name": "Soporte de altavoz mural",
        "family": "Pared",
        "description": "Pequeño estante mural paramétrico para altavoces y dispositivos similares.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/speaker-wall-mount.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "wall-cable-clip": {
        "name": "Clip mural de cable",
        "family": "Cableado",
        "description": "Clip mural configurable para guiar uno o varios cables junto a una superficie.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/wall-cable-clip.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "light-clamp-block": {
        "name": "Bloc de sujeción ligera",
        "family": "Maker",
        "description": "Bloque paramétrico para sujeciones ligeras y prototipos de taller.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/light-clamp-block.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "cutting-guide": {
        "name": "Guía de corte",
        "family": "Maker",
        "description": "Guía recta paramétrica para posicionamiento y referencia en trabajos manuales.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/cutting-guide.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "parametric-spacer": {
        "name": "Separador / calzo paramétrico",
        "family": "Maker",
        "description": "Calzo configurable con base y escalón para ajustes, montaje y nivelación.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/parametric-spacer.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "bit-key-organizer": {
        "name": "Organizador de brocas / llaves",
        "family": "Maker",
        "description": "Organizador modular con divisiones configurables para brocas y herramientas pequeñas.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/bit-key-organizer.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "parametric-lidded-box": {
        "name": "Caja paramétrica con tapa",
        "family": "Organización",
        "description": "Caja configurable con paredes, base y tapa independiente para uso general.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/parametric-lidded-box.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "stackable-box": {
        "name": "Caja apilable",
        "family": "Organización",
        "description": "Caja paramétrica con borde superior preparada para organización modular.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/stackable-box.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "modular-tray": {
        "name": "Bandeja modular",
        "family": "Organización",
        "description": "Bandeja abierta con divisor central y dimensiones configurables.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/modular-tray.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "desk-organizer": {
        "name": "Organizador de escritorio",
        "family": "Organización",
        "description": "Organizador multi-bahía para material de oficina y accesorios técnicos.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/desk-organizer.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "modular-pen-holder": {
        "name": "Portabolígrafos modular",
        "family": "Organización",
        "description": "Portabolígrafos paramétrico con varias celdas cilíndricas.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/modular-pen-holder.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "hardware-box": {
        "name": "Caja para tornillería",
        "family": "Organización",
        "description": "Caja compartimentada configurable para tornillos, conectores y piezas pequeñas.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/hardware-box.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "accessory-rack": {
        "name": "Rack pequeño de accesorios",
        "family": "Organización",
        "description": "Rack paramétrico con varios niveles para piezas y accesorios ligeros.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/accessory-rack.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "inset-label": {
        "name": "Etiqueta / placa encastrable",
        "family": "Maker",
        "description": "Etiqueta paramétrica con pestaña para identificación e integración en otras piezas.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/inset-label.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "sd-card-organizer": {
        "name": "Organizador de tarjetas SD",
        "family": "Organización",
        "description": "Organizador compacto con múltiples separadores para tarjetas y piezas finas.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/sd-card-organizer.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
    "cable-reel": {
        "name": "Carrete organizador de cable",
        "family": "Cableado",
        "description": "Carrete paramétrico con núcleo y bridas laterales para ordenar cable sobrante.",
        "tips": ["Mide el objeto real antes de imprimir","Valida el resultado en el visor 3D"],
        "marketing_image": "/images/products/premium-v1/cable-reel.webp",
        "stage": "production",
        "visual_source": "studio_asset",
    },
}

PRODUCTION_STAGES = {"production"}
PUBLIC_STAGES = {"production"}
LAB_STAGES = {"engineering", "visual_qa", "production"}

def metadata_for(slug: str) -> dict:
    return dict(PRODUCT_METADATA.get(slug, {}))
